#!/bin/bash
determin_hwmon() {
name=amdgpu
num=1
marker=0
while [ $marker -eq 0 ]
do
	eval=$(cat "/sys/class/hwmon/hwmon$num/name")
	if [ "$eval" = "$name" ]
		then
		enablefile=/sys/class/hwmon/hwmon$num/pwm1_enable
		pwmfile=/sys/class/hwmon/hwmon$num/pwm1
		marker=1
	else
		let num++
	fi
done
}
determin_hwmon
sudo echo 1 > $enablefile
read_speed() {
curr=$(cat $pwmfile)
}
set_speed() {
sudo echo $speed > $pwmfile
echo speed set to $speed
}
if [ "$1" = "-s" ]
then
read_speed
echo "Current Speed: $curr / 255"
exit
fi
if [ "$1" = "-S" ]
then
read_speed
echo "$curr"
exit
fi
if [ "$1" = "-g" ]
then
echo entered graphical mode using zenity
g_speed=$(zenity --scale --title "AMDGPU fan speed" --text "Choose fan speed 1-255" --min-value=1 --max-value=255 --step=5 --value=45)
if [ -z "$g_speed" ]
then
echo "nothing set, exitting"
exit
else
speed=$g_speed
set_speed
fi
exit
fi
read_speed
echo "current speed $curr / 255"
echo "type desired speed: "
if [ -z "$1" ]
then
read speed && set_speed
else
speed=$1 && set_speed
fi
